print("Following values evaluated to True")
print('bool("True") : ', bool("True"))
print('bool("false") : ', bool("false"))
print('bool("False") : ', bool("False"))
print('bool("Yes") : ', bool("Yes"))
print('bool("No") : ', bool("No"))
print('bool("0") : ', bool("0"))
print('bool("0.0") : ', bool("0.0"))
print('bool("1") : ', bool("1"))
print('bool([2, 3]) : ', bool([2, 3]))
print('bool({"id" : 1}) : ', bool({"id":1}))
print('bool(True) : ', bool(True))

print("\nFollowing values evaluated to False")
print('bool(0) : ', bool(0))
print('bool(0.0) : ', bool(0.0))
print('bool([]) : ', bool([]))
print('bool({}) : ', bool({}))
print('bool(()) : ', bool(()))
print('bool(set()) : ', bool(set()))
print('bool(None) : ', bool(None))
print('bool(False) : ', bool(False))